# Generated by Django 6.0.5 on 2026-05-19 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('artist', models.CharField(db_index=True, max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(max_length=1000, unique=True)),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Downloaded Track',
                'verbose_name_plural': 'Downloaded Tracks',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
